import { c as create_ssr_component, e as escape, b as add_attribute, v as validate_component } from "../../chunks/ssr.js";
import { T as Testimonials } from "../../chunks/Testimonials.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: "header.svelte-15g15wu.svelte-15g15wu.svelte-15g15wu{overflow:hidden;height:100vh;max-height:800px}.home-hero.svelte-15g15wu.svelte-15g15wu.svelte-15g15wu{display:grid;grid-template-columns:1fr 1fr;align-items:center}.home-hero-text.svelte-15g15wu.svelte-15g15wu.svelte-15g15wu{max-width:600px}.home-hero-text.svelte-15g15wu p.svelte-15g15wu.svelte-15g15wu{margin-bottom:1rem}header.svelte-15g15wu img.svelte-15g15wu.svelte-15g15wu{height:100%;width:100%;overflow:hidden}.button-wrap.svelte-15g15wu.svelte-15g15wu.svelte-15g15wu{display:flex;align-items:center;gap:1rem;margin-top:3rem}.button-wrap.svelte-15g15wu a.svelte-15g15wu.svelte-15g15wu{margin-top:0}.grid-image.svelte-15g15wu.svelte-15g15wu.svelte-15g15wu{width:100%;max-width:635px}.home-hero-icon-grid.svelte-15g15wu.svelte-15g15wu.svelte-15g15wu{display:grid;grid-template-columns:1fr 1fr;grid-gap:1rem;margin:3rem 0}.icon-item-wrapper.svelte-15g15wu img.svelte-15g15wu.svelte-15g15wu{height:50px;width:50px;margin-bottom:1rem}.grid-col-3.svelte-15g15wu div.svelte-15g15wu img.svelte-15g15wu{margin-bottom:1rem}.grid-col-3.svelte-15g15wu div.svelte-15g15wu h3.svelte-15g15wu{font-size:2rem}.cta-full-width.svelte-15g15wu.svelte-15g15wu.svelte-15g15wu{background-image:url(/images/cta-banner.jpg);background-position:center;background-size:cover;background-repeat:no-repeat;width:100%;height:420px;text-align:center;color:var(--white);position:relative;display:flex;align-items:center;justify-content:center}.banner-overlay.svelte-15g15wu.svelte-15g15wu.svelte-15g15wu{background-color:rgba(47, 101, 229, 0.9);width:100%;height:100%;position:absolute;top:0}.z-index.svelte-15g15wu.svelte-15g15wu.svelte-15g15wu{z-index:10}.is-secondary.svelte-15g15wu.svelte-15g15wu.svelte-15g15wu{margin-top:2rem}@media screen and (max-width: 961px){.home-hero.svelte-15g15wu.svelte-15g15wu.svelte-15g15wu{display:flex;flex-direction:column;gap:3rem}header.svelte-15g15wu img.svelte-15g15wu.svelte-15g15wu{position:static;left:550px;top:50px;height:100%;width:100%}.home-hero-icon-grid.svelte-15g15wu.svelte-15g15wu.svelte-15g15wu{display:flex;flex-direction:column}}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { title = "Dove Design Ltd | Home" } = $$props;
  let { description = "At Dove Design, we specialise in creating visually appealing and highly functional websites that help businesses succeed online." } = $$props;
  if ($$props.title === void 0 && $$bindings.title && title !== void 0)
    $$bindings.title(title);
  if ($$props.description === void 0 && $$bindings.description && description !== void 0)
    $$bindings.description(description);
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-1law5hj_START -->${$$result.title = `<title>${escape(title)}</title>`, ""}<meta name="description"${add_attribute("content", description, 0)}><!-- HEAD_svelte-1law5hj_END -->`, ""} <header class="svelte-15g15wu" data-svelte-h="svelte-1pz0rcg"><div class="container svelte-15g15wu"><div class="home-hero svelte-15g15wu"><div class="home-hero-text svelte-15g15wu"><h1>Transforming businesses with <span>stunning websites</span></h1> <p class="svelte-15g15wu">At Dove Design, we specialise in creating visually appealing and
          highly functional websites that help businesses succeed online. Our
          team of experts combines design and technology to deliver exceptional
          user experiences.</p> <div class="button-wrap svelte-15g15wu"><a class="button svelte-15g15wu" href="/contact">Contact Us</a> <a class="is-secondary svelte-15g15wu" href="/work">Our Work</a></div></div> <img src="/images/home-hero.png" alt="Dove Design Portfolio screenshots" class="svelte-15g15wu"></div></div></header> <section data-svelte-h="svelte-nzbgdt"><div class="container svelte-15g15wu"><div class="grid-col-2 svelte-15g15wu"><div class="home-hero-text svelte-15g15wu"><p class="section-kicker svelte-15g15wu">How can we help</p> <h2>Experts in Web <span>Design</span> &amp; Web <span>Development</span></h2> <p class="svelte-15g15wu">At Dove Design, we offer a range of services to help businesses
          succeed online. Our team of experts specialises in design,
          development, and maintenance, ensuring that your website is visually
          stunning, user-friendly, and always up to date.</p> <p class="svelte-15g15wu">Whether you need a brand new website or want to enhance your existing
          one, we have the skills and expertise to deliver exceptional results.</p> <div class="home-hero-icon-grid svelte-15g15wu"><div class="icon-item-wrapper svelte-15g15wu"><img src="/images/design.svg" alt="paint pallette" class="svelte-15g15wu"> <h3 class="svelte-15g15wu">Web Design</h3> <p class="svelte-15g15wu">Our team of skilled designers transforms your ideas into visually
              stunning, user-friendly websites that not only meet but exceed
              your expectations.</p></div> <div class="icon-item-wrapper svelte-15g15wu"><img src="/images/responsive.svg" alt="responsive web design" class="svelte-15g15wu"> <h3 class="svelte-15g15wu">Web Development</h3> <p class="svelte-15g15wu">We bring your website to life with custom development solutions
              that are tailored to your business needs and objectives.</p></div> <div class="icon-item-wrapper svelte-15g15wu"><img src="/images/hosting.svg" alt="hosting websites" class="svelte-15g15wu"> <h3 class="svelte-15g15wu">Website Hosting</h3> <p class="svelte-15g15wu">Enjoy the fastest, most scalable hosting technology for your
              business powered by super fast web services.</p></div> <div class="icon-item-wrapper svelte-15g15wu"><img src="/images/medal.svg" alt="blue medal" class="svelte-15g15wu"> <h3 class="svelte-15g15wu">Training</h3> <p class="svelte-15g15wu">We offer virtual training sessions to your staff on how to update
              the website with video tutorials.</p></div></div> <a class="button" href="/contact">Contact us</a></div> <img class="grid-image svelte-15g15wu" src="/images/section-image.webp" alt="Flowga studios screenshots"></div></div></section> <section data-svelte-h="svelte-1kdzg7i"><div class="container"><div class="grid-col-2"><div><p class="section-kicker">Why Dove Design</p> <h2>Unlock the potential of the web for your <span>business</span></h2></div> <p>Webflow is a powerful tool that empowers businesses to create stunning
        and functional websites without the need for coding. With its intuitive
        interface and robust features, Webflow streamlines the web design
        process and allows businesses to focus on what they do best.</p></div> <div class="grid-col-3 svelte-15g15wu"><div><img src="/images/tick.svg" alt="tick" class="svelte-15g15wu"> <h3 class="svelte-15g15wu">Empowered control</h3> <p>With Webflow, clients can make updates and edits to their websites
          without relying on developers. This hands-on approach saves time and
          money, putting you in charge of your digital presence.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-15g15wu"> <h3 class="svelte-15g15wu">Responsive websites</h3> <p>Webflow ensures your website looks stunning and functions seamlessly
          on all devices. Mobile users will have a smooth and engaging
          experience.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-15g15wu"> <h3 class="svelte-15g15wu">Lightning-fast hosting</h3> <p>Powered by Amazon Web Services with 100+ server sites globally,
          content is delivered in milliseconds.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-15g15wu"> <h3 class="svelte-15g15wu">Search engine visibility</h3> <p>Webflow incorporates SEO best practices, ensuring your website ranks
          well on search engines. This translates to increased organic traffic
          and potential customers.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-15g15wu"> <h3 class="svelte-15g15wu">Top grade security</h3> <p>Comes with SSL and two-factor authentication out of the box. You can
          also password protect individual pages.</p></div> <div><img src="/images/tick.svg" alt="tick" class="svelte-15g15wu"> <h3 class="svelte-15g15wu">First class support</h3> <p>Webflow&#39;s responsive support team is ready to assist with any
          questions or issues. You&#39;ll have peace of mind knowing there&#39;s a
          dedicated team to help you achieve your website goals.</p></div></div> <a class="button" href="/contact">Contact us</a></div></section> <section class="cta-full-width svelte-15g15wu" data-svelte-h="svelte-qwep9h"><div class="banner-overlay svelte-15g15wu"></div> <div class="container z-index svelte-15g15wu"><h2>Web Design Experts</h2> <p>Empower Your Online Identity with Tailored Design Magic</p> <a href="/work"><button class="is-secondary svelte-15g15wu">View Our Work</button></a></div></section> ${validate_component(Testimonials, "Testimonials").$$render($$result, {}, {}, {})}`;
});
export {
  Page as default
};
