import { c as create_ssr_component, e as escape, b as add_attribute, f as each } from "../../../../chunks/ssr.js";
import { p as projects } from "../../../../chunks/projectData.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: ".container.svelte-o5issc.svelte-o5issc{display:flex;flex-direction:column;align-items:center;max-width:1240px}.tags-wrapper.svelte-o5issc.svelte-o5issc{display:flex;flex-direction:row;gap:1rem}.tags.svelte-o5issc p.svelte-o5issc{background-color:#eee;color:var(--accent-blue);padding:0.5rem 1rem;border-radius:5px}.client-wrapper.svelte-o5issc.svelte-o5issc{display:flex;flex-direction:row;justify-content:space-evenly;margin-top:2rem;gap:3rem;width:100%}.client-item.svelte-o5issc.svelte-o5issc{display:flex;flex-direction:column;gap:1rem;text-align:center}h1.svelte-o5issc.svelte-o5issc{text-align:center}img.svelte-o5issc.svelte-o5issc{margin-bottom:2rem}h2.svelte-o5issc.svelte-o5issc{margin-top:2rem}p.svelte-o5issc.svelte-o5issc{margin-bottom:1rem;white-space:pre-line}a.svelte-o5issc.svelte-o5issc{color:var(--accent-blue)}.testimonial-wrapper.svelte-o5issc.svelte-o5issc{text-align:center;max-width:800px}.testimonial-wrapper.svelte-o5issc h3.svelte-o5issc{font-size:1.25rem;line-height:1.6}.testimonial-wrapper.svelte-o5issc img.svelte-o5issc{margin-top:1rem}.testimonial-wrapper.svelte-o5issc p.svelte-o5issc{font-weight:bold;margin-bottom:0}@media(max-width: 768px){.client-wrapper.svelte-o5issc.svelte-o5issc{flex-direction:column;gap:1rem}h2.svelte-o5issc.svelte-o5issc{margin-top:1rem}}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-bifkuz_START -->${$$result.title = `<title>${escape(projects[0].name)} | Dove Design Ltd | Real Client Success Stories</title>`, ""}<meta name="description" content="This page showcases the Durham Police and Crime Commissioner website that was build to help the service to offer services to help support people in the community."><meta property="og:image" content="/images/open-graph.jpg"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Dove Design Ltd"><meta property="og:image:type" content="image/jpeg"><meta property="og:image:secure_url" content="/images/open-graph.jpg"><!-- HEAD_svelte-bifkuz_END -->`, ""} <section><div class="container project-container svelte-o5issc"><img${add_attribute("src", projects[0].heroImage, 0)} alt="Durham PCC Logo" class="svelte-o5issc"> <h1 class="project-heading svelte-o5issc">${escape(projects[0].name)}</h1> <div class="tags-wrapper svelte-o5issc">${each(projects[0].tags, (tag) => {
    return `<div class="tags svelte-o5issc"><p class="svelte-o5issc">${escape(tag)}</p> </div>`;
  })}</div> <div class="client-wrapper svelte-o5issc"><div class="client-item svelte-o5issc"><h3 data-svelte-h="svelte-1cnkhaf">Client</h3> <p class="svelte-o5issc">${escape(projects[0].clientName)}</p></div> <div class="client-item svelte-o5issc"><h3 data-svelte-h="svelte-h4ffs9">Website</h3> <a href="https://www.durham-pcc.gov.uk" target="_blank" class="svelte-o5issc">${escape(projects[0].website)}</a></div> <div class="client-item svelte-o5issc"><h3 data-svelte-h="svelte-1ym5djk">Date</h3> <p class="svelte-o5issc">${escape(projects[0].date)}</p></div></div> <h2 class="svelte-o5issc" data-svelte-h="svelte-1se8v5d">Overview</h2> <p class="project-description svelte-o5issc">${escape(projects[0].overview)}</p> <h2 class="svelte-o5issc" data-svelte-h="svelte-1lwxwnj">What We Did</h2> <p class="project-description svelte-o5issc">${escape(projects[0].whatWeDid)}</p> <h2 class="svelte-o5issc" data-svelte-h="svelte-1eudpfj">The Outcome</h2> <p class="project-description svelte-o5issc">${escape(projects[0].outcome)}</p></div></section>  <section><div class="container svelte-o5issc"><div class="testimonial-wrapper svelte-o5issc"><h3 class="svelte-o5issc">${escape(projects[0].testimonialQuote)}</h3> <img${add_attribute("src", projects[0].crest, 0)} alt="Durham PCC Logo" class="svelte-o5issc"> <p class="svelte-o5issc">${escape(projects[0].testimonialName)}</p> <p style="font-weight: 400;" class="svelte-o5issc">${escape(projects[0].testimonialTitle)}</p></div></div></section>  `;
});
export {
  Page as default
};
